"""Add Category model

Revision ID: 72ee6cd57810
Revises: 2060f37bc23f
Create Date: 2026-07-01 12:18:03.970028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ee6cd57810'
down_revision: Union[str, Sequence[str], None] = '2060f37bc23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.add_column('screenshots', sa.Column('category_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_screenshots_category_id'), 'screenshots', ['category_id'], unique=False)
    op.create_foreign_key(None, 'screenshots', 'categories', ['category_id'], ['id'], ondelete='SET NULL')

    # --- Custom Data Migration ---
    import uuid
    bind = op.get_bind()
    
    # Get distinct categories per user
    result = bind.execute(sa.text("SELECT DISTINCT user_id, category FROM screenshots WHERE category IS NOT NULL AND category != ''"))
    
    for row in result:
        user_id = row[0]
        cat_name = row[1]
        cat_id = str(uuid.uuid4())
        
        # Insert new category
        bind.execute(
            sa.text("INSERT INTO categories (id, user_id, name, created_at) VALUES (:id, :uid, :name, NOW())"),
            {"id": cat_id, "uid": user_id, "name": cat_name}
        )
        
        # Link screenshots to the new category_id
        bind.execute(
            sa.text("UPDATE screenshots SET category_id = :cat_id WHERE user_id = :uid AND category = :name"),
            {"cat_id": cat_id, "uid": user_id, "name": cat_name}
        )
    # -----------------------------
    op.drop_column('screenshots', 'subcategory')
    op.drop_column('screenshots', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshots', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('screenshots', sa.Column('subcategory', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'screenshots', type_='foreignkey')
    op.drop_index(op.f('ix_screenshots_category_id'), table_name='screenshots')
    op.drop_column('screenshots', 'category_id')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
