"""Add session_id and make user_id nullable

Revision ID: 955be28cb52e
Revises: 72ee6cd57810
Create Date: 2026-07-03 10:22:43.119914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955be28cb52e'
down_revision: Union[str, Sequence[str], None] = '72ee6cd57810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshots', sa.Column('session_id', sa.String(), nullable=True))
    op.alter_column('screenshots', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_screenshots_session_id'), 'screenshots', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshots_session_id'), table_name='screenshots')
    op.alter_column('screenshots', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('screenshots', 'session_id')
    # ### end Alembic commands ###
