"""Add session_id to categories and make user_id nullable

Revision ID: c3b9f04c053b
Revises: 955be28cb52e
Create Date: 2026-07-03 13:44:43.226910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b9f04c053b'
down_revision: Union[str, Sequence[str], None] = '955be28cb52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('session_id', sa.String(), nullable=True))
    op.alter_column('categories', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_categories_session_id'), 'categories', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_session_id'), table_name='categories')
    op.alter_column('categories', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('categories', 'session_id')
    # ### end Alembic commands ###
